name: Deploy website

on:
  push:
    tags:
      - 'v*' # Run only when a tag is pushed with a version format like 'v1.0.0'

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      - name: Minify tailwindcss
        run: npx tailwindcss -i ./src/tailwind.css -o ./css/tailwind.css --minify

      -name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      #-name: Upload files to S3
      #  run |
      #    aws s3 cp index.html s3://${{ secrets.AWS_S3_BUCKET_NAME }}/
      #    aws s3 cp css/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}/ --recursive
      #    aws s3 cp images/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}/ --recursive
