name: Deploy website

on:
  push:
    tags:
      - 'v*' # Run only when a tag is pushed with a version format like 'v1.0.0'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      #- name: Minify tailwindcss
      #  run: npx tailwindcss -i ./src/tailwind.css -o ./css/tailwind.css --minify
      - name: Build website
        run: |
          mkdir -p deploy/css
          mkdir -p deploy/images
          cp index.html ./deploy/index.html
          cp error.html ./deploy/error.html
          cp  images/* ./deploy/images/
          cp css/fonts.css ./deploy/css/fonts.css
          npx tailwindcss -i ./src/tailwind.css -o ./deploy/css/tailwind.css --minify

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Upload files to S3
        run: |
          aws s3 sync deploy/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}/ --delete
          aws s3 sync deploy/ s3://${{ secrets.AWS_S3_BUCKET_NAME2 }}/ --delete
          rm -rf deploy
