name: Deploy website

on:
  push:
    tags:
      - 'v*' # Run only when a tag is pushed with a version format like 'v1.0.0'

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      - name: Minify tailwindcss
        run: npx tailwindcss -i ./src/tailwind.css -o ./css/tailwind.css -o --minify